
spring:
  datasource:
    password: 1qaz@WSX
    url: jdbc:mysql://localhost:3306/employeemanager
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
